export const properties = [
  {
    id: 1,
    title: "Modern Downtown Apartment",
    location: "Downtown, San Francisco, CA",
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Apartment",
    availableFrom: "Jan 15",
    features: ["Gym", "Pool", "Parking", "Pet Friendly"],
    isLiked: false
  },
  {
    id: 2,
    title: "Luxury Penthouse with City Views",
    location: "Upper East Side, New York, NY",
    price: 8500,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    image: "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Penthouse",
    availableFrom: "Feb 1",
    features: ["Concierge", "Rooftop", "Gym", "Doorman"],
    isLiked: true
  },
  {
    id: 3,
    title: "Cozy Studio in Arts District",
    location: "Arts District, Los Angeles, CA",
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: "https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Studio",
    availableFrom: "Now",
    features: ["WiFi", "Laundry", "AC", "Furnished"],
    isLiked: false
  },
  {
    id: 4,
    title: "Family Home with Garden",
    location: "Suburbs, Austin, TX",
    price: 2500,
    bedrooms: 4,
    bathrooms: 3,
    area: 2000,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "House",
    availableFrom: "Mar 1",
    features: ["Garden", "Garage", "Fireplace", "Pet Friendly"],
    isLiked: false
  },
  {
    id: 5,
    title: "Waterfront Condo",
    location: "Marina District, Seattle, WA",
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: "https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Condo",
    availableFrom: "Feb 15",
    features: ["Water View", "Balcony", "Pool", "Gym"],
    isLiked: true
  },
  {
    id: 6,
    title: "Historic Brownstone",
    location: "Brooklyn Heights, New York, NY",
    price: 5800,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Townhouse",
    availableFrom: "Jan 30",
    features: ["Historic", "Hardwood", "Fireplace", "Garden"],
    isLiked: false
  },
  {
    id: 7,
    title: "Mountain View Retreat",
    location: "Boulder, Colorado, CO",
    price: 3800,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    image: "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "House",
    availableFrom: "Apr 1",
    features: ["Mountain View", "Deck", "Fireplace", "Hiking"],
    isLiked: false
  },
  {
    id: 8,
    title: "Beach House Paradise",
    location: "Venice Beach, Los Angeles, CA",
    price: 6500,
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    image: "https://images.pexels.com/photos/1396125/pexels-photo-1396125.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "House",
    availableFrom: "Mar 15",
    features: ["Beach Access", "Deck", "BBQ", "Parking"],
    isLiked: true
  },
  {
    id: 9,
    title: "Industrial Loft",
    location: "SoHo, New York, NY",
    price: 7200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1800,
    image: "https://images.pexels.com/photos/1571450/pexels-photo-1571450.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Loft",
    availableFrom: "Feb 20",
    features: ["High Ceilings", "Exposed Brick", "Elevator", "Skylights"],
    isLiked: false
  },
  {
    id: 10,
    title: "Charming Cottage",
    location: "Napa Valley, CA",
    price: 2800,
    bedrooms: 2,
    bathrooms: 1,
    area: 1000,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Cottage",
    availableFrom: "Mar 10",
    features: ["Wine Country", "Garden", "Fireplace", "Pet Friendly"],
    isLiked: false
  },
  {
    id: 11,
    title: "Urban Loft with Rooftop",
    location: "Downtown, Chicago, IL",
    price: 4800,
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Loft",
    availableFrom: "Feb 25",
    features: ["Rooftop", "Gym", "City View", "WiFi"],
    isLiked: true
  },
  {
    id: 12,
    title: "Suburban Family Villa",
    location: "Plano, TX",
    price: 3500,
    bedrooms: 5,
    bathrooms: 4,
    area: 2800,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Villa",
    availableFrom: "Apr 15",
    features: ["Garage", "Garden", "Playroom", "Pool"],
    isLiked: false
  },
  {
    id: 13,
    title: "Luxury Lakefront Villa",
    location: "Lake Tahoe, NV",
    price: 9200,
    bedrooms: 6,
    bathrooms: 5,
    area: 4000,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Villa",
    availableFrom: "Jun 1",
    features: ["Lake View", "Boat Dock", "Jacuzzi", "Sauna"],
    isLiked: true
  },
  {
    id: 14,
    title: "Compact Studio",
    location: "Downtown, Miami, FL",
    price: 1500,
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Studio",
    availableFrom: "Now",
    features: ["AC", "WiFi", "Laundry", "Furnished"],
    isLiked: false
  },
  {
    id: 15,
    title: "Skyline Penthouse",
    location: "Downtown, Houston, TX",
    price: 8800,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Penthouse",
    availableFrom: "Mar 25",
    features: ["Rooftop", "Gym", "Concierge", "Infinity Pool"],
    isLiked: true
  },
  {
    id: 16,
    title: "Countryside Ranch",
    location: "Santa Fe, NM",
    price: 2600,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Ranch",
    availableFrom: "May 1",
    features: ["Barn", "Stable", "Land", "Fireplace"],
    isLiked: false
  },
  {
    id: 17,
    title: "Desert Villa",
    location: "Scottsdale, AZ",
    price: 5300,
    bedrooms: 4,
    bathrooms: 3,
    area: 2300,
    image: "https://images.pexels.com/photos/221506/pexels-photo-221506.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Villa",
    availableFrom: "Apr 5",
    features: ["Pool", "Deck", "Desert View", "Garage"],
    isLiked: false
  },
  {
    id: 18,
    title: "Eco-Friendly Apartment",
    location: "Portland, OR",
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Apartment",
    availableFrom: "Now",
    features: ["Solar Panels", "Green Roof", "WiFi", "Parking"],
    isLiked: true
  },
  {
    id: 19,
    title: "Ski Chalet",
    location: "Aspen, CO",
    price: 7600,
    bedrooms: 5,
    bathrooms: 4,
    area: 3000,
    image: "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Chalet",
    availableFrom: "Dec 15",
    features: ["Ski Access", "Fireplace", "Sauna", "Mountain View"],
    isLiked: false
  },
  {
    id: 20,
    title: "Luxury Downtown Condo",
    location: "Boston, MA",
    price: 5500,
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    image: "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Condo",
    availableFrom: "Feb 28",
    features: ["Concierge", "Gym", "Pool", "Balcony"],
    isLiked: true
  },
  {
    id: 21,
    title: "Forest Cabin",
    location: "Smoky Mountains, TN",
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    image: "https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Cabin",
    availableFrom: "Mar 12",
    features: ["Wood Stove", "Hiking Trails", "Deck", "Pet Friendly"],
    isLiked: false
  },
  {
    id: 22,
    title: "Luxury Townhouse",
    location: "Georgetown, Washington DC",
    price: 6700,
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Townhouse",
    availableFrom: "Apr 12",
    features: ["Historic", "Balcony", "Garage", "Fireplace"],
    isLiked: true
  },
  {
    id: 23,
    title: "Suburban Condo",
    location: "San Jose, CA",
    price: 3100,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    image: "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Condo",
    availableFrom: "Mar 8",
    features: ["Gym", "Pool", "WiFi", "Parking"],
    isLiked: false
  },
  {
    id: 24,
    title: "Clifftop Villa",
    location: "Malibu, CA",
    price: 12500,
    bedrooms: 6,
    bathrooms: 6,
    area: 5000,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Villa",
    availableFrom: "Jun 10",
    features: ["Ocean View", "Infinity Pool", "Cinema", "Sauna"],
    isLiked: true
  },
  {
    id: 25,
    title: "Riverside Apartment",
    location: "Portland, ME",
    price: 2600,
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Apartment",
    availableFrom: "Feb 22",
    features: ["River View", "Balcony", "WiFi", "Parking"],
    isLiked: false
  },
  {
    id: 26,
    title: "Rustic Farmhouse",
    location: "Lancaster, PA",
    price: 2200,
    bedrooms: 4,
    bathrooms: 2,
    area: 2000,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Farmhouse",
    availableFrom: "May 20",
    features: ["Barn", "Garden", "Garage", "Fireplace"],
    isLiked: false
  },
  {
    id: 27,
    title: "High-Rise Condo",
    location: "Downtown, Atlanta, GA",
    price: 3900,
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Condo",
    availableFrom: "Mar 18",
    features: ["Rooftop", "Gym", "Concierge", "Pool"],
    isLiked: true
  },
  {
    id: 28,
    title: "Hilltop Mansion",
    location: "Beverly Hills, CA",
    price: 18000,
    bedrooms: 8,
    bathrooms: 9,
    area: 10000,
    image: "https://images.pexels.com/photos/221506/pexels-photo-221506.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Mansion",
    availableFrom: "Jul 1",
    features: ["Cinema", "Sauna", "Wine Cellar", "Infinity Pool"],
    isLiked: true
  },
  {
    id: 29,
    title: "Downtown Studio",
    location: "Seattle, WA",
    price: 1700,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    image: "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Studio",
    availableFrom: "Now",
    features: ["WiFi", "Laundry", "AC", "Furnished"],
    isLiked: false
  },
  {
    id: 30,
    title: "Modern Duplex",
    location: "Austin, TX",
    price: 3400,
    bedrooms: 3,
    bathrooms: 2,
    area: 1700,
    image: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=800",
    type: "Duplex",
    availableFrom: "Apr 18",
    features: ["Garage", "Garden", "Balcony", "Pet Friendly"],
    isLiked: false
  }
];
