export const sampleHomes = [
  {
    id: '1',
    title: 'Luxury Beachfront Villa',
    location: 'Malibu, California',
    price: 450,
    rating: 4.9,
    reviews: 127,
    image: 'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    amenities: ['Ocean View', 'Private Pool', 'WiFi', 'Kitchen', 'Parking'],
    description: 'Stunning beachfront villa with panoramic ocean views and private beach access.'
  },
  {
    id: '2',
    title: 'Cozy Mountain Cabin',
    location: 'Aspen, Colorado',
    price: 280,
    rating: 4.7,
    reviews: 89,
    image: 'https://images.pexels.com/photos/417238/pexels-photo-417238.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    amenities: ['Mountain View', 'Fireplace', 'Hot Tub', 'WiFi', 'Ski Access'],
    description: 'Charming mountain retreat perfect for ski trips and cozy evenings by the fire.'
  },
  {
    id: '3',
    title: 'Modern City Loft',
    location: 'New York, NY',
    price: 320,
    rating: 4.8,
    reviews: 203,
    image: 'https://images.pexels.com/photos/2290753/pexels-photo-2290753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: ['City View', 'Modern Kitchen', 'WiFi', 'Gym Access', 'Rooftop'],
    description: 'Sleek modern loft in the heart of Manhattan with stunning city skyline views.'
  },
  {
    id: '4',
    title: 'Tropical Paradise Bungalow',
    location: 'Bora Bora, French Polynesia',
    price: 650,
    rating: 5.0,
    reviews: 78,
    image: 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    amenities: ['Overwater', 'Snorkeling', 'Private Deck', 'WiFi', 'Kayak'],
    description: 'Overwater bungalow with crystal clear lagoon views and world-class snorkeling.'
  },
  {
    id: '5',
    title: 'Historic Countryside Manor',
    location: 'Tuscany, Italy',
    price: 380,
    rating: 4.6,
    reviews: 156,
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 5,
    bathrooms: 4,
    guests: 10,
    amenities: ['Wine Cellar', 'Garden', 'Pool', 'WiFi', 'Historic'],
    description: 'Restored 16th-century manor house surrounded by rolling hills and vineyards.'
  },
  {
    id: '6',
    title: 'Desert Oasis Retreat',
    location: 'Scottsdale, Arizona',
    price: 290,
    rating: 4.5,
    reviews: 92,
    image: 'https://images.pexels.com/photos/1488267/pexels-photo-1488267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    amenities: ['Desert View', 'Pool', 'Spa', 'WiFi', 'Golf Access'],
    description: 'Luxurious desert retreat with stunning mountain views and resort-style amenities.'
  }
];
